# Generated by Django 4.1.3 on 2023-03-01 11:10

from django.db import migrations, models
import django.db.models.deletion
import validators.custom_validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('university_code', models.CharField(max_length=50, unique=True, validators=[validators.custom_validators.validate_only_digits])),
                ('city_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.city')),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('faculty_code', models.CharField(max_length=50, unique=True, validators=[validators.custom_validators.validate_only_digits])),
                ('university_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.university')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('department_code', models.CharField(max_length=50, unique=True, validators=[validators.custom_validators.validate_only_digits])),
                ('faculty_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.faculty')),
            ],
        ),
    ]
