# Generated by Django 4.1.3 on 2023-03-14 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_alter_city_city_code_alter_city_name_and_more'),
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='faculty_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.faculty', verbose_name='دانشکده/ واحد'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=250, verbose_name='گروه'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='name',
            field=models.CharField(max_length=250, verbose_name='دانشکده'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='university_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.university', verbose_name='واحد (دانشگاه)'),
        ),
        migrations.AlterField(
            model_name='university',
            name='city_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.city', verbose_name='شهر'),
        ),
        migrations.AlterField(
            model_name='university',
            name='name',
            field=models.CharField(max_length=250, verbose_name='واحد (دانشگاه)'),
        ),
    ]
