# Generated by Django 4.1.3 on 2023-04-22 20:05

from django.db import migrations, models
import validators.custom_validators


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0003_alter_department_faculty_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='faculty_code',
            field=models.CharField(max_length=50, validators=[validators.custom_validators.validate_only_digits]),
        ),
        migrations.AlterUniqueTogether(
            name='faculty',
            unique_together={('faculty_code', 'university_id')},
        ),
    ]
