# Generated by Django 4.1.3 on 2023-04-22 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0004_alter_faculty_faculty_code_and_more'),
        ('major', '0002_remove_major_degree_id_remove_major_group_id_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='major',
            unique_together={('major_id', 'department_id')},
        ),
    ]
