# Generated by Django 4.1.3 on 2023-03-01 11:10

import django.core.validators
from django.db import migrations, models
import validators.custom_validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('course_code', models.CharField(max_length=50, validators=[validators.custom_validators.validate_only_digits])),
                ('course_type', models.CharField(choices=[('جبراني', 'جبراني'), ('اختياري', 'اختياري'), ('علوم وابسته دانشكده اي', 'علوم وابسته دانشكده اي'), ('عمومي', 'عمومي'), ('پايه', 'پايه'), ('اصلي', 'اصلي'), ('تخصصي', 'تخصصي'), ('پيش دانشگاهي', 'پيش دانشگاهي'), ('علوم پايه اختصاصي', 'علوم پايه اختصاصي'), ('علوم پايه مشترك', 'علوم پايه مشترك'), ('صلاحيت مدرسي', 'صلاحيت مدرسي'), ('علوم وابسته بيمارستاني', 'علوم وابسته بيمارستاني'), ('الزامي', 'الزامي'), ('پروژه/پایان نامه/رساله', 'پروژه/پایان نامه/رساله'), ('مهارت هاي عملي', 'مهارت هاي عملي'), ('سمينار', 'سمينار'), ('کاروزي', 'کاروزي'), ('کارآموزي در عرصه', 'کارآموزي در عرصه'), ('کلینیکی', 'کلینیکی')], max_length=50)),
                ('theoretical_credit', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(25)])),
                ('practical_credit', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(25)])),
            ],
        ),
    ]
