# Generated by Django 4.1.3 on 2023-03-14 09:32

from django.db import migrations, models
import validators.custom_validators


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_code',
            field=models.CharField(max_length=50, unique=True, validators=[validators.custom_validators.validate_only_digits]),
        ),
    ]
