# Generated by Django 4.1.3 on 2023-03-16 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classroom', '0001_initial'),
        ('course_status', '0001_initial'),
        ('course_offering', '0002_rename_day_courseoffering_weekday'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseHolding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_holding_type', models.CharField(choices=[('normal', 'عادی'), ('makeup', 'جبرانی'), ('extra', 'کلاس اضافه')], max_length=20)),
                ('weekday', models.CharField(choices=[('SATURDAY', 'شنبه'), ('SUNDAY', 'یکشنبه'), ('MONDAY', 'دوشنبه'), ('TUESDAY', 'سه شنبه'), ('WEDNESDAY', 'چهارشنبه'), ('THURSDAY', 'پنج شنبه'), ('FRIDAY', 'جمعه')], max_length=20)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom.classroom')),
                ('course_status', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='course_status.coursestatus')),
                ('offered_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_offering.courseoffering')),
            ],
        ),
    ]
