# Generated by Django 4.1.3 on 2023-03-17 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0001_initial'),
        ('course_holding', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseholding',
            name='professor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='professor.professor'),
        ),
    ]
