# Generated by Django 4.1.3 on 2023-03-18 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_holding', '0002_courseholding_professor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseholding',
            old_name='professor',
            new_name='professor_id',
        ),
    ]
