# Generated by Django 4.1.3 on 2023-04-03 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_holding', '0004_remove_courseholding_weekday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseholding',
            name='course_holding_type',
            field=models.CharField(choices=[('NORMAL', 'عادی'), ('MAKEUP', 'جبرانی'), ('EXTRA', 'کلاس اضافه')], max_length=20),
        ),
    ]
