# Generated by Django 4.1.3 on 2023-03-01 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classroom', '0001_initial'),
        ('professor', '0001_initial'),
        ('major', '0001_initial'),
        ('semester', '0001_initial'),
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseOfferingFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('file', models.FileField(upload_to='files/')),
                ('upload', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CourseOffering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('SATURDAY', 'شنبه'), ('SUNDAY', 'یکشنبه'), ('MONDAY', 'دوشنبه'), ('TUESDAY', 'سه شنبه'), ('WEDNESDAY', 'چهارشنبه'), ('THURSDAY', 'پنج شنبه'), ('FRIDAY', 'جمعه')], max_length=20)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('offering_course_code', models.CharField(max_length=50, unique=True)),
                ('aggregate', models.BooleanField(default=False)),
                ('course_gender', models.CharField(choices=[('BOTH', 'فرقی ندارد'), ('MALE', 'مرد'), ('FEMALE', 'زن')], max_length=20)),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom.classroom')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course')),
                ('major_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='major.major')),
                ('professor_id', models.ManyToManyField(to='professor.professor')),
                ('semester_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='semester.semester')),
            ],
        ),
    ]
