# Generated by Django 4.1.3 on 2023-03-30 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('major', '0001_initial'),
        ('course_offering', '0002_rename_day_courseoffering_weekday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseoffering',
            name='major_id',
        ),
        migrations.AddField(
            model_name='courseoffering',
            name='major_id',
            field=models.ManyToManyField(to='major.major'),
        ),
    ]
