# Generated by Django 4.1.3 on 2023-04-22 20:05

from django.db import migrations, models
import validators.custom_validators


class Migration(migrations.Migration):

    dependencies = [
        ('course_offering', '0003_remove_courseoffering_major_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseoffering',
            name='offering_course_code',
            field=models.CharField(max_length=50, unique=True, validators=[validators.custom_validators.validate_only_digits]),
        ),
    ]
