# Generated by Django 4.1.3 on 2023-02-12 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('holiday', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='holiday',
            old_name='holiday_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='holiday',
            old_name='holiday_name',
            new_name='name',
        ),
    ]
