# Generated by Django 4.1.3 on 2023-03-01 11:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import validators.custom_validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('professor_code', models.CharField(max_length=50, unique=True, validators=[validators.custom_validators.validate_only_digits])),
                ('is_active', models.BooleanField(default=True)),
                ('gender', models.CharField(choices=[('MALE', 'مرد'), ('FEMALE', 'زن')], max_length=20)),
                ('course_list', models.ManyToManyField(to='course.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
