# Generated by Django 4.1.3 on 2023-04-01 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0002_alter_professor_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='professor',
            old_name='course_list',
            new_name='course_id',
        ),
    ]
