# Generated by Django 4.1.3 on 2023-03-01 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_city_class_course_courseofferingfile_degree_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='province_id',
        ),
        migrations.RemoveField(
            model_name='class',
            name='faculty_id',
        ),
        migrations.RemoveField(
            model_name='courseoffering',
            name='class_id',
        ),
        migrations.RemoveField(
            model_name='courseoffering',
            name='course_id',
        ),
        migrations.RemoveField(
            model_name='courseoffering',
            name='major_id',
        ),
        migrations.RemoveField(
            model_name='courseoffering',
            name='professor_id',
        ),
        migrations.RemoveField(
            model_name='courseoffering',
            name='semester_id',
        ),
        migrations.DeleteModel(
            name='CourseOfferingFile',
        ),
        migrations.RemoveField(
            model_name='department',
            name='faculty_id',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='university_id',
        ),
        migrations.RemoveField(
            model_name='major',
            name='degree_id',
        ),
        migrations.RemoveField(
            model_name='major',
            name='department_id',
        ),
        migrations.RemoveField(
            model_name='major',
            name='group_id',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='course_list',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='user',
        ),
        migrations.RemoveField(
            model_name='university',
            name='city_id',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Class',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='CourseOffering',
        ),
        migrations.DeleteModel(
            name='Degree',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Faculty',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.DeleteModel(
            name='Major',
        ),
        migrations.DeleteModel(
            name='Professor',
        ),
        migrations.DeleteModel(
            name='Province',
        ),
        migrations.DeleteModel(
            name='Semester',
        ),
        migrations.DeleteModel(
            name='University',
        ),
    ]
