# Generated by Django 4.1.3 on 2023-03-01 11:10

import django.core.validators
from django.db import migrations, models
import validators.custom_validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, editable=False, max_length=250)),
                ('year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1380)])),
                ('semester_type', models.IntegerField(choices=[(1, 'نیمسال اول'), (2, 'نیمسال دوم'), (3, 'تابستان')])),
                ('semester_code', models.CharField(max_length=50, validators=[validators.custom_validators.validate_only_digits])),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
    ]
