# Generated by Django 4.1.3 on 2023-03-14 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0002_alter_department_faculty_id_alter_department_name_and_more'),
        ('semester', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='university_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='university.university'),
            preserve_default=False,
        ),
    ]
