# Generated by Django 4.1.3 on 2023-03-16 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('WAITING', 'Waiting'), ('PRESENT', 'Present'), ('ABSENT', 'Absent')], default='WAITING', max_length=10)),
                ('delay_amount', models.PositiveSmallIntegerField(default=0)),
                ('hurry_amount', models.PositiveSmallIntegerField(default=0)),
                ('description', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
