# Generated by Django 4.1.3 on 2023-03-17 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_status', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursestatus',
            name='description',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
