# Generated by Django 4.1.3 on 2023-04-12 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_status', '0002_alter_coursestatus_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursestatus',
            name='state',
        ),
        migrations.AddField(
            model_name='coursestatus',
            name='status',
            field=models.CharField(choices=[('WAITING', 'Waiting'), ('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('OFFICIAL_HOLIDAY', 'Official holiday'), ('UNEXPECTED_HOLIDAY', 'Unexpected holiday')], default='WAITING', max_length=20),
        ),
    ]
