# Generated by Django 4.1.3 on 2023-04-17 04:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='floor',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(20)]),
        ),
    ]
