# Generated by Django 4.1.3 on 2023-04-22 20:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_alter_classroom_floor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='class_number',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(1000000)]),
        ),
    ]
