# Generated by Django 4.1.3 on 2023-03-01 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('province_code', models.PositiveSmallIntegerField(db_index=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('city_code', models.PositiveSmallIntegerField(db_index=True, unique=True)),
                ('province_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.province')),
            ],
        ),
    ]
