# Generated by Django 4.1.3 on 2023-03-14 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='city_code',
            field=models.PositiveSmallIntegerField(db_index=True, unique=True, verbose_name='کد شهر'),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=250, verbose_name='شهر'),
        ),
        migrations.AlterField(
            model_name='city',
            name='province_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.province', verbose_name='استان'),
        ),
        migrations.AlterField(
            model_name='province',
            name='name',
            field=models.CharField(max_length=250, verbose_name='استان'),
        ),
        migrations.AlterField(
            model_name='province',
            name='province_code',
            field=models.PositiveSmallIntegerField(db_index=True, unique=True, verbose_name='کد استان'),
        ),
    ]
