# Generated by Django 4.1.3 on 2022-11-27 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[('UNIVERSITY', 'university'), ('FACULTY', 'faculty'), ('DEPARTMENT', 'department'), ('PROFESSOR', 'professor'), ('EMPLOYEE', 'employee')], null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
