# Generated by Django 4.1.3 on 2023-02-04 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_user_role_alter_user_email_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_role',
            field=models.CharField(choices=[('None', 'انتخاب کنید'), ('UNIVERSITY', 'رییس دانشگاه'), ('FACULTY', 'رییس دانشکده'), ('DEPARTMENT', 'مدیر گروه'), ('PROFESSOR', 'استاد'), ('EMPLOYEE', 'کارمند'), ('AMOZESH', 'آموزش'), ('ADMIN', 'ادمین')], default='None', max_length=50),
        ),
    ]
