# Generated by Django 4.1.3 on 2023-03-01 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('major', '0001_initial'),
        ('university', '0001_initial'),
        ('account', '0003_alter_user_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='major_id',
            field=models.ManyToManyField(to='major.major'),
        ),
        migrations.AddField(
            model_name='user',
            name='university_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='university.university'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_role',
            field=models.CharField(choices=[('UNIVERSITY', 'رییس دانشگاه'), ('FACULTY', 'رییس دانشکده'), ('DEPARTMENT', 'مدیر گروه'), ('PROFESSOR', 'استاد'), ('EMPLOYEE', 'کارمند'), ('MANAGER', 'آموزش'), ('GENERAL_MANAGER', 'آموزش کل'), ('ADMIN', 'ادمین')], max_length=50),
        ),
    ]
