# Generated by Django 4.1.3 on 2023-03-21 10:10

from django.db import migrations, models
import django.db.models.deletion
import validators.custom_validators


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0002_alter_department_faculty_id_alter_department_name_and_more'),
        ('account', '0004_user_major_id_user_university_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='faculty_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='university.faculty'),
        ),
        migrations.AlterField(
            model_name='user',
            name='university_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='university.university'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=50, unique=True, validators=[validators.custom_validators.validate_username]),
        ),
    ]
