# Generated by Django 4.1.3 on 2023-03-21 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('major', '0001_initial'),
        ('account', '0005_user_faculty_id_alter_user_university_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='major_id',
            field=models.ManyToManyField(blank=True, null=True, to='major.major'),
        ),
    ]
