# Generated by Django 4.1.3 on 2023-04-03 13:23

import account.custom_fields
from django.db import migrations, models
import validators.custom_validators


class Migration(migrations.Migration):

    dependencies = [
        ('major', '0002_remove_major_degree_id_remove_major_group_id_and_more'),
        ('account', '0006_alter_user_major_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=account.custom_fields.CaseInsensitiveEmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='major_id',
            field=models.ManyToManyField(blank=True, to='major.major'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=account.custom_fields.CaseInsensitiveUsernameField(max_length=50, unique=True, validators=[validators.custom_validators.validate_username]),
        ),
    ]
